server:
  port: ${SERVER_PORT:8047}
  servlet:
    context-path: /
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/demanduck?useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: info
    com:
      nib: debug