server:
  port: 8045
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://172.22.116.156:3306/demanduck?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.22.116.156
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
      timeout: 10000
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    root: info
    com:
      nib: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0