server:
  port: 8047
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demanduck?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
      timeout: 10000
logging:
  level:
    root: info
    com:
      nib: debug