server:
  port: 8047
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/demanduck?useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: info
    com:
      nib: debug